!/bin/bash

#deifining the variables
myusername=$USER
host_name=$(hostname)
up_time=$(uptime | awk '{print $2,$3}' | tr -d ',')
model_name=$(lscpu | grep "Model name" | awk '{print$3,$4,$5}')
Max_speed=$(sudo dmidecode -t processor | grep "Max Speed" | awk '{print $3,$4; exit}')

#showing username and cureent date and time
echo "
System Report generated by $myusername, $(date +"%F %T")

#showing system information 
System Information 
-------------
Hostname: $host_name"

source /etc/os-release
echo "
OS: $PRETTY_NAME
Uptime: $up_time

#hardware information
Hardware Information
----------------------
cpu: $model_name
Speed: $(sudo lshw -class processor | awk '/size:/{print $2; exit}')
Maximum Speed: $Max_speed
Ram: $(free -h | awk '/^Mem:/{print $2}')
Disk(s):
$(lsblk -o NAME,MODEL,SIZE | grep '^s') 
Video: $(sudo lshw -C display | awk '/vendor:|product:/ {print $2,$3,$4,""}' | tr -d '\n')

#Network information 
Network Information
---------------------
FQDN: $(hostname --fqdn)
Host Address: $(hostname -I | cut -d ' ' -f 1)
Gateway IP: $(ip r | awk '/default via/ {print $3}')
DNS Server: $(awk '/nameserver/ {print $2}' /etc/resolv.conf)

InterfaceName: $(sudo lshw -class network | awk '/description: Ethernet interface/ {getline; print $2,$3,$4,$5; getline; print $2,$3; exit}')
IP Address: $(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}') 

#Displaying Status of the system  
System Status
--------------
Users Logged In: $(who | awk '{print $1}' | sort | uniq | paste -s -d ',')
Disk Space: $(df -h --output=target,avail | awk '!/ Filesystem/ {print $1, $2}')
Process Count: $(ps -ef | wc -l)
Load Averages: $(uptime | awk -F'average:' '{print $2}')
Memory Allocation: $(free -h | awk '/^Mem:/ {print "Total Memory:", $2, "Used Memory:", $3, "Free Memory:", $4}')
Listening Network Ports: $(sudo ss -tuln)
UFW Rules: $(sudo ufw status numbered | grep -v 'Status: active')
"



